plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '1.0.21'
}

repositories {
    mavenLocal()
    maven { url = 'https://neoforged.forgecdn.net/releases' }
    maven { url = 'https://neoforged.forgecdn.net/mojang-meta' }
    maven { url = "https://api.modrinth.com/maven" }
    mavenCentral()
}

ext {
    jade_version = "15.10.5+neoforge"
}

version = '1.1.0-1.21.1'
base.archivesName = 'CloudWorksAPI'

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = '21.1.186'

    runs {
        client {
            client()
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        cloudworks_api {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "maven.modrinth:jade:${jade_version}"
}

processResources {
    from(sourceSets.main.resources.srcDirs) {
        include '**'
        expand 'file.jarVersion': project.version
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}