/*
 * CloudWorks API - Unified Recipe Parsing Interface
 * Copyright (C) 2026 CloudWorks Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package com.cloudworks.api.recipeparser.dsl;

/**
 * Token generated by the tokenizer.
 *
 * 璇嶆硶鍒嗘瀽鍣ㄧ敓鎴愮殑 Token銆?
 * <p>
 * 姣忎釜 Token 鍖呭惈涓€涓被鍨嬪拰涓€涓彲閫夌殑瀛楃涓插€笺€?
 * 鐢ㄤ簬琛ㄧず RPML 妯℃澘鏂囦欢缁忚繃璇嶆硶鍒嗘瀽鍚庣殑鏈€灏忚涔夊崟鍏冦€?
 * </p>
 */
public class Token {
    /**
     * Token type
     */
    /** Token 绫诲瀷 */
    public final TokenType type;
    /**
     * Token value, meaningful for literal types; for symbol types, the corresponding symbol character
     */
    /** Token 鐨勫€硷紝瀵逛簬瀛楅潰閲忕被鍨嬫湁鎰忎箟锛屽浜庣鍙风被鍨嬩负瀵瑰簲鐨勭鍙峰瓧绗?*/
    public final String value;

    /**
 * Constructs a Token instance.
 *
 * 鏋勯€犱竴涓?Token 瀹炰緥銆?
 *
 * @param type the token type
 * @param value the token value
 * @param type  Token 绫诲瀷
 * @param value Token 鐨勫€?
 */
    public Token(TokenType type, String value) {
        this.type = type;
        this.value = value;
    }

    @Override
    public String toString() {
        return type + "(" + value + ")";
    }
}